version : '3'

services:

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432"
    env_file: .env
    networks: 
      - kong-network
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:

networks:
  kong-network:
    driver: bridge